// src/constants/events.js
export const WS_EVENTS = {
  STATE_UPDATE: 'STATE_UPDATE',
  SPIN_START: 'SPIN_START',
  ADMIN_AUTH_SUCCESS: 'ADMIN_AUTH_SUCCESS',
  USERS_COUNT: 'USERS_COUNT',
  ERROR: 'ERROR',
  AUTH_ADMIN: 'AUTH_ADMIN',
  UPDATE_PRIZES: 'UPDATE_PRIZES',
  START_SPIN: 'START_SPIN',
};
